name: weather_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  auto_route: ^8.1.3
  iconsax: ^0.0.8
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  get_storage: ^2.1.1
  dartz: ^0.10.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  http: ^1.2.1
  dio: ^5.4.3+1
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
